package laws
object Instances { val all = Map(
"Array[Int]" -> (Array[Int]((0 to 0): _*)),
"collection.IndexedSeq[Int]" -> (collection.IndexedSeq[Int]((0 to 0): _*)),
"collection.Iterable[Int]" -> (collection.Iterable[Int]((0 to 0): _*)),
"collection.Iterator[Int]" -> (((0 to 0)).iterator),
"collection.LinearSeq[Int]" -> (collection.LinearSeq[Int]((0 to 0): _*)),
"collection.Seq[Int]" -> (collection.Seq[Int]((0 to 0): _*)),
"collection.Set[Int]" -> ((collection.Set.empty[Int] ++(0 to 0))),
"collection.SortedSet[Int]" -> ((collection.SortedSet.empty[Int] ++(0 to 0))),
"collection.TraversableOnce[Int]" -> ((((0 to 0)).iterator: collection.TraversableOnce[Int])),
"collection.Traversable[Int]" -> (collection.Traversable[Int]((0 to 0): _*)),
"collection.immutable.BitSet" -> (collection.immutable.BitSet((0 to 0): _*)),
"collection.immutable.HashSet[Int]" -> ((collection.immutable.HashSet.empty[Int] ++(0 to 0))),
"collection.immutable.IndexedSeq[Int]" -> (collection.immutable.IndexedSeq[Int]((0 to 0): _*)),
"collection.immutable.Iterable[Int]" -> (collection.immutable.Iterable[Int]((0 to 0): _*)),
"collection.immutable.LinearSeq[Int]" -> (collection.immutable.LinearSeq[Int]((0 to 0): _*)),
"collection.immutable.ListSet[Int]" -> ((collection.immutable.ListSet.empty[Int] ++(0 to 0))),
"collection.immutable.List[Int]" -> (collection.immutable.List[Int]((0 to 0): _*)),
"collection.immutable.PagedSeq[Int]" -> (({ val temp =(0 to 0); new collection.immutable.PagedSeq[Int]((a,i,j) => { val t2 = temp.slice(i,j); var k=i; t2.foreach{ x => a(k) = x; k+=1 }; k-i }) })),
"collection.immutable.Queue[Int]" -> (collection.immutable.Queue((0 to 0): _*)),
"collection.immutable.Range" -> (((0 to 0))),
"collection.immutable.Seq[Int]" -> (collection.immutable.Seq((0 to 0): _*)),
"collection.immutable.Set[Int]" -> ((collection.immutable.Set.empty[Int] ++(0 to 0))),
"collection.immutable.SortedSet[Int]" -> ((collection.immutable.SortedSet.empty[Int] ++(0 to 0))),
"collection.immutable.Stack[Int]" -> (collection.immutable.Stack((0 to 0): _*)),
"collection.immutable.Stream[Int]" -> (((0 to 0)).toStream),
"collection.immutable.Traversable[Int]" -> (collection.immutable.Traversable((0 to 0): _*)),
"collection.immutable.Vector[Int]" -> (collection.immutable.Vector[Int]((0 to 0): _*)),
"collection.mutable.ArrayBuffer[Int]" -> (collection.mutable.ArrayBuffer[Int]((0 to 0): _*)),
"collection.mutable.ArraySeq[Int]" -> (collection.mutable.ArraySeq[Int]((0 to 0): _*)),
"collection.mutable.ArrayStack[Int]" -> (collection.mutable.ArrayStack[Int]((0 to 0): _*)),
"collection.mutable.BitSet" -> ((collection.mutable.BitSet.empty ++(0 to 0))),
"collection.mutable.Buffer[Int]" -> (collection.mutable.Buffer[Int]((0 to 0): _*)),
"collection.mutable.DoubleLinkedList[Int]" -> (collection.mutable.DoubleLinkedList[Int]((0 to 0): _*)),
"collection.mutable.HashSet[Int]" -> ((collection.mutable.HashSet.empty[Int] ++(0 to 0))),
"collection.mutable.IndexedSeq[Int]" -> (collection.mutable.IndexedSeq[Int]((0 to 0): _*)),
"collection.mutable.Iterable[Int]" -> (collection.mutable.Iterable[Int]((0 to 0): _*)),
"collection.mutable.LinearSeq[Int]" -> (collection.mutable.LinearSeq[Int]((0 to 0): _*)),
"collection.mutable.LinkedHashSet[Int]" -> ((collection.mutable.LinkedHashSet.empty[Int] ++(0 to 0))),
"collection.mutable.LinkedList[Int]" -> (collection.mutable.LinkedList[Int]((0 to 0): _*)),
"collection.mutable.ListBuffer[Int]" -> (collection.mutable.ListBuffer[Int]((0 to 0): _*)),
"collection.mutable.MutableList[Int]" -> (collection.mutable.MutableList[Int]((0 to 0): _*)),
"collection.mutable.PriorityQueue[Int]" -> (collection.mutable.PriorityQueue[Int]((0 to 0): _*)),
"collection.mutable.Queue[Int]" -> (collection.mutable.Queue[Int]((0 to 0): _*)),
"collection.mutable.ResizableArray[Int]" -> (collection.mutable.ResizableArray[Int]((0 to 0): _*)),
"collection.mutable.Seq[Int]" -> (collection.mutable.Seq[Int]((0 to 0): _*)),
"collection.mutable.Set[Int]" -> ((collection.mutable.Set.empty[Int] ++(0 to 0))),
"collection.mutable.SortedSet[Int]" -> ((collection.mutable.SortedSet.empty[Int] ++(0 to 0))),
"collection.mutable.Stack[Int]" -> (collection.mutable.Stack[Int]((0 to 0): _*)),
"collection.mutable.Traversable[Int]" -> (collection.mutable.Traversable[Int]((0 to 0): _*)),
"collection.mutable.TreeSet[Int]" -> ((collection.mutable.TreeSet.empty[Int] ++(0 to 0))),
"collection.mutable.UnrolledBuffer[Int]" -> (collection.mutable.UnrolledBuffer[Int]((0 to 0): _*)),
"collection.mutable.WrappedArray[Int]" -> ((Array[Int]((0 to 0): _*): collection.mutable.WrappedArray[Int])),
  "" -> null)
}
